version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: finance_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "22653:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/FinanceTest.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "Host=db;Port=5432;Database=finance_test;Username=postgres;Password=123456"
    depends_on:
      - db

volumes:
  postgres_data: